version: "3"
services:
  backend: 
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - /backend/src
  frontend:
    volumes:
      - /frontend/src
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "9091:80"
    depends_on:
      - backend
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: sts
      MYSQL_ROOT_HOST: "%"
