services:
  front:
    build:
      context:
        ./frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      DB_HOST: db
    ports:
      - "3000:3000"
      - "5173:5173"
    networks:
      sts_network:
        ipv4_address: 172.22.0.20
  

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8882:80
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 300M
    depends_on:
      - db  
    networks:
        sts_network:
          ipv4_address: 172.22.0.22

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yourdatabase
      MYSQL_USER: youruser
      MYSQL_PASSWORD: yourpassword
    networks:
      sts_network:
        ipv4_address: 172.22.0.23
    volumes:
      - db_data:/var/lib/mysql
          

  nginx:
    image: nginx:latest
    ports:
      - "8890:80"
      - "443:443"
    volumes:
    - ./nginx:/etc/nginx/conf.d
    - ./nginx/html:/usr/share/nginx/html
    networks:
        sts_network:
          ipv4_address: 172.22.0.24

  back:
    build: ./backend
    restart: always
    environment:
      DB_USERNAME: youruser
      DB_PASSWORD: yourpassword
    volumes:
      - ./backend:/app
      - ./backend/logs:/app/logs
    depends_on:
      - db
    ports:
      - "4000:4000"
    networks:
      sts_network:
        ipv4_address: 172.22.0.21

volumes:
  mysql:
  db_data:

networks:
  sts_network:
    external: true