version: "3"
services:
  backend: 
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./backend/node_modules:/backend/node_modules
  frontend:
    volumes:
      - ./frontend/node_modules:/frontend/node_modules
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "9091:80"
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: sts
      MYSQL_ROOT_HOST: "%"
